### ISSUE TITLE
Setting current directory: no such file or directory

### ISSUE THREAD

**Issue by padget** [syohex/emacs-helm-gtags#102]
Hi Syohex

I have a problem with the function helm-gtags-dwim. I work under emacs 24.4 in cygwin (windows 7).
I have the following error message : 

Setting current directory: no such file or directory, D:/Exe/Cygwin/dev/brain^M/.
However, the right path is /dev/brain/ . Is helm gtags compatible with emacs under cygwin ?

Is there a solution ?

Thanks for your answer.

**Comment by syohex** [comment]
Which Emacs do you use ? Cygwin package Emacs or Windows native Emacs(such as Emacs for Windows , NTEmacs etc) ?

And would you tell me result of `M-: (helm-gtags--windows-p)` ?

**Comment by padget** [comment]
I use cygwin package emacs

The evaluation of (helm-gtags--windows-p) return nil.

**Comment by syohex** [comment]
I suppose that this is caused by that `global` command outputs are Windows path style
like `C:\foo\bar`, while Emacs of cygwin package expects Unix path style like `/foo/bar`.

**Comment by syohex** [comment]
@padget Would you check following version ?
(Download it and replace current version with it)

https://raw.githubusercontent.com/syohex/emacs-helm-gtags/80eaf2aeb3ebd015e5164bbf56243a8bfbbd1711/helm-gtags.el

**Comment by padget** [comment]
Thanks, it seems to be fixed.
On what kind of references this function runs ?
When i tried on variable, a popup appears and propose me all files where a variable with the same name is. It is normal ?

**Comment by syohex** [comment]
> Thanks, it seems to be fixed.

Thanks for checking.

> When i tried on variable, a popup appears and propose me all files where a variable with the same name is. It is normal ?

Yes it is normal. GNU global don't know defined point of variables.

**Comment by padget** [comment]
ok thanks for all :)

**Comment by tnielens** [comment]
Hello, 
I run emacs cygwin also but I have compiled global from sources with the cygwin environment and I have the opposite problem, global wants unix paths and it gets dos paths, hehe ..  :)
