### ISSUE TITLE
Jump to files in GTAGSLIBPATH

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-helm-gtags#115]
I wonder whether it's possible to jump to a file in GTAGSLIBPATH with GNU Global. If so, we should add it. For example, I have include files in GTAGSLIBPATH but currently `helm-gtags-dwim` cannot jump to the file.

**Comment by syohex** [comment]
Hmm, I cannot reproduce this issue. Would you tell me how to reproduce this issue in detail ?

**Comment by kleesc** [comment]
I'm having a similar issue. When using global from the command line it actually finds the tags in GTAGSLIBPATH. In emacs however, running helm-gtags-dwim over a system header include doesn't do anything. So the issue is probably related to helm rather than global itself.

**Comment by syohex** [comment]
@kleesc Would you tell me how to reproduce this issue in detail ?

**Comment by rhexo** [comment]
hi, i have the same problem.

in my .emacs file i put:
(setenv "GTAGSLIBPATH" "/home/rhexo/.gtags/")

then in shell do some commands:
mkdir ~/.gtags
#For common c includes make symbolic link
ln -s /usr/include usr-include
# For c++ includes like <map>, <string> and so on make symbolic link
ln -s /usr/include/c++/4.8 usr-include-cxx-4_8  
gtags -c

restart emacs.

open my cpp file and try to jump in <string> with "M-.", but dose no magic happen :(

PS: for local includes in my projects all works fine! And in shell command like this: global string returns multiple paths result.

**Comment by rhexo** [comment]
I'm using helm-gtags from melpa repo.
And thanks for your wokr, this is realy amazing tool :)

**Comment by syohex** [comment]
> open my cpp file and try to jump in #include <string> with "M-.", but dose no magic happen :(

helm-gtags-dwim jumps to header file if cursor is on include statement. Then helm-gtags calls  `global --path`, but `--path` option does not support files under `GTAGSLIBPATH`.

**Comment by syohex** [comment]
@rhexo I have implemented to search in directories of GTAGSLIBPATH at #120. Please check latest version.

**Comment by rhexo** [comment]
@syohex this works!
Thank you!
