### ISSUE TITLE
helm-gtags-dwim cannot be used in non-file buffer

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-helm-gtags#116]
To reproduce:

- Navigate to a project root and generate tags there. Assume that the project has a tag `main`.
- `M-x compile` then run this command `echo main()`
- After the compilation buffer appears, move point to `main()` text.
- Run `helm-gtags-dwim` and error occurs, while `helm-gtags-find-tag` or `helm-gtags-find-rtags` works perfectly fine.

This is useful when you one to quickly jump with gtags on console output i.e. results from test cases.

**Comment by syohex** [comment]
I have fixed at #117. Please check latest version.
