### ISSUE TITLE
Failed: create TAGS(1)

### ISSUE THREAD

**Issue by zwb-ict** [syohex/emacs-helm-gtags#119]
My system info: Mac OSX 10.10
global version: 6.5

When I M-x helm-gtags-create-tags, helm-gtags throws error: Failed: create TAGS(1)

**Comment by zwb-ict** [comment]
Emacs: 24.5.4 (brew)

**Comment by syohex** [comment]
Do you set permission correctly ?
Please check `gtags` at the directory in terminal emulator.

**Comment by zwb-ict** [comment]
@syohex, I can run **gtags** in terminal emulator, I use brew to install global, this is my permission:

lrwxr-xr-x  1 zwb  admin    30B  7 13 18:40 gtags -> ../Cellar/global/6.5/bin/gtags

**Comment by syohex** [comment]
Thanks

> Do you set permission correctly ?

Sorry, this means the directory permission where you failed `M-x helm-gtags-create-tags`. And please try to execute `gtags` the directory where you failed `M-x helm-gtags-create-tags` in terminal.

**Comment by zwb-ict** [comment]
@syohex  I ran gtags in my project's directory, it works OK, creates three files with data.

**Comment by syohex** [comment]
Hmm, I cannot reproduce. Can you reproduce this issue in other directory ?

**Comment by zwb-ict** [comment]
@syohex , I can reproduce this issue in other directory.

**Comment by zwb-ict** [comment]
@syohex It can create three files, but the files are empty.

**Comment by syohex** [comment]
Can I download your project(or project where you happen this issue) from somewhere ?

**Comment by zwb-ict** [comment]
@syohex, I have a question, what's the difference between "default", "native", "ctags", "pyments"? I use default, it works OK, I chose ctags, it gave me this error.

**Comment by syohex** [comment]
> I have a question, what's the difference between "default", "native", "ctags", "pyments"? I use default, it works OK, I chose ctags, it gave me this error.

They are parsers. GNU global supports some parsers. GNU global parsers supports a few languages(C, C++, Java, old PHP), while `ctags` and `pygments` supports much languages(C, C++, Ruby, Python, Golang etc) than GNU global ones. However you need to configure GNU global with those options and install them.

I suppose you can install gnu global with those features by following command.

```
% brew uninstall global
% brew install global --with-exuberant-ctags --with-pygments
```

**Comment by zwb-ict** [comment]
@syohex Thank you very much! I reinstall global with these params, It now works OK!
