### ISSUE TITLE
helm-gtags-select in the recent helm-gtags fails to work

### ISSUE THREAD

**Issue by oracleyue** [syohex/emacs-helm-gtags#121]
The `helm-gtags-select` does not work well in the most recent `helm-gtags`.
**Could you confirm this bug? Could I fix it by configurations?** Thanks a lot!

The expected behavior of `helm-gtags-select` is shown in http://tuhdo.github.io/c-ide.html, illustrated as
![helm-gtags-select](https://cloud.githubusercontent.com/assets/5046605/9295305/a838194e-4469-11e5-9239-0b66e012951c.gif)

However, when I call `helm-gtags-select`, I successfully got a list. However, when hitting `<TAB>`, I got an error, and failed to switch to any path or show any lists, as illustrated below:
<img width="728" alt="helm-gtags-select-malfunction" src="https://cloud.githubusercontent.com/assets/5046605/9295304/836bbcb0-4469-11e5-92d6-fe547f6732d6.png">
When I hit `<ENTER>`, I got another error, as illustrated below:
<img width="728" alt="helm-gtags-select-malfunction2" src="https://cloud.githubusercontent.com/assets/5046605/9295318/08114732-446a-11e5-9bb9-cb8f588b22b2.png">

Version: 
Emacs 24.4.1
Helm 2015.08.15.740
Helm-gtags 2015.08.15.50

Configuration in init files:
```elisp
;; Prefix config
(setq
 helm-gtags-ignore-case t
 helm-gtags-auto-update t
 helm-gtags-use-input-at-cursor t
 helm-gtags-pulse-at-cursor t
 helm-gtags-prefix-key "\C-cg"
 helm-gtags-suggested-key-mapping t
 helm-gtags-auto-update t
 ;helm-gtags-cache-select-result t
 )
(require 'helm-gtags)
;; Enable helm-gtags-mode
(add-hook 'dired-mode-hook 'helm-gtags-mode)
(add-hook 'eshell-mode-hook 'helm-gtags-mode)
(add-hook 'c-mode-hook 'helm-gtags-mode)
(add-hook 'c++-mode-hook 'helm-gtags-mode)
```

**Comment by syohex** [comment]
I suppose this is `helm-run-after-quit` issue. I have replaced it with timer at #122.
Please wait.

**Comment by syohex** [comment]
I have merged #122. Please check latest version.

**Comment by oracleyue** [comment]
@syohex Thanks a lot!!
I prefer to install it from elpa. So I will close this issue after checking it when elpa is updated. Many thanks for your prompt response!

**Comment by oracleyue** [comment]
@syohex Thanks a lot!!
I will close this issue after checking it. Many thanks for your prompt response!
