### ISSUE TITLE
when i run helm-gtags-create-tags, /usr/bin/gtags-parser consume all my cpu.

### ISSUE THREAD

**Issue by yuandaxing** [syohex/emacs-helm-gtags#127]
my environment is:
ubuntu 15.04, GNU Emacs 24.5.1

when i run helm-gtags-create-tags under some directory:
for example: 
a/b/c/
but i find two process /usr/bin/gtags-parser, run like below
/usr/bin/gtags-parser  a/b/boost/f.cpp  a/b/boost/c.cpp
it use up my cpu.

**Comment by syohex** [comment]
Which gnu global version do you use ? Debian/Ubuntu GNU global package is too old and too slow. If you use older version, please try to use newer version.

Official document(https://www.gnu.org/software/global/download.html) says

> It's too old. Please don't use Debian's package

**Comment by yuandaxing** [comment]
➜  trunk git:(master) global --version
global - GNU GLOBAL 5.7.1

i will try the new version.

**Comment by yuandaxing** [comment]
thanks @syohex , resolved, i will close this issue.

**Comment by syohex** [comment]
:+1:
