### ISSUE TITLE
helm-gtags-path-style set to 'relative is broken

### ISSUE THREAD

**Issue by jacekmigacz** [syohex/emacs-helm-gtags#131]
When you browse results in helm frame and peek using **helm-execute-persistent-action**, then with **helm-gtags-path-style** set to **'relative** path to the selected file is constructed wrongly. To duplicate this issue you have to browse non-flat source tree (like *torvalds/linux*). I observed it on both *POSIX* and *MSWIN* platforms.
At least, please take off ***'(helm-gtags-path-style 'relative)*** from sample configuration on the main page.

**Comment by syohex** [comment]
Could you tell me how to reproduce this issue in more detail ?

![test](https://cloud.githubusercontent.com/assets/554281/10961552/3a6ad952-83d3-11e5-8638-722cb766364d.gif)

It seems that it works well.

**Comment by jacekmigacz** [comment]
**completion** symbol was found in the same file, at the same dir-level. Problem occurs with multiple directories.

Please try something like this:
![131](https://cloud.githubusercontent.com/assets/1120058/10962031/8aad474a-8349-11e5-940c-46dc170e355a.gif)

**Comment by syohex** [comment]
@jacekmigacz I have merged #132. Could you check latest version ?

**Comment by jacekmigacz** [comment]
@syohex I tried de0c1c0 and with ```helm-gtags-path-style's value is relative``` I can't tell the diffrence between relative and root.
![zrzut ekranu z 2015-11-05 22-22-25](https://cloud.githubusercontent.com/assets/1120058/10990792/eca0278e-840b-11e5-97b3-912ec5a4735e.png)
![zrzut ekranu z 2015-11-05 22-23-27](https://cloud.githubusercontent.com/assets/1120058/10990800/fc794e60-840b-11e5-91df-4d714ea0b89d.png)

**Comment by jacekmigacz** [comment]
@syohex please ignore last my comment.

**Comment by jacekmigacz** [comment]
@syohex de0c1c000c050d73dcf4f4330965f64b74d5548d is working fine.
![de0c1c000c050d73dcf4f4330965f64b74d5548d](https://cloud.githubusercontent.com/assets/1120058/10990999/2cdb9976-840e-11e5-84db-b74d41dc76dd.gif)
