### ISSUE TITLE
one GTAGSLIBPATH per project

### ISSUE THREAD

**Issue by brunoqc** [syohex/emacs-helm-gtags#134]
Is there a way to have differents GTAGSLIBPATH depending of which project I'm in?

For example, I don't want to have tags from the Linux kernel when I'm doing other stuff.

**Comment by syohex** [comment]
> Is there a way to have differents GTAGSLIBPATH depending of which project I'm in?

Sorry no way now. You need to set manually now by such as following command.

```lisp
(defun my/setenv-gtagslibpath (dir)
  (interactive
   (list (read-directory-name "Library Path: ")))
  (setenv "GTAGSLIBPATH" (expand-file-name dir)))
```

**Comment by brunoqc** [comment]
Thanks.
