### ISSUE TITLE
golden-ratio-mode is incompatible with helm-gtags

### ISSUE THREAD

**Issue by amosbird** [syohex/emacs-helm-gtags#135]
There is a bug with `golden-ratio-mode`.  `helm-gtags-dwim-other-window` will create a new window instead of reusing existing one.
![sxov taa wurzbf9_d5c wc](https://cloud.githubusercontent.com/assets/5085485/11556070/663cec1a-99df-11e5-9f54-1669989012f7.png)

**Comment by syohex** [comment]
At first, helm-gtags does not provide `helm-gtags-dwim-other-window` command.

Action of `Open file other window` uses just `find-file-other-window` which is a emacs built-in function.

**Comment by amosbird** [comment]
@syohex Do you suggest that it is a bug of `golden-ratio-mode`? However `find-file-other-window` works just fine.

**Comment by amosbird** [comment]
This seems to be a `Windows only issue`.
