### ISSUE TITLE
Jumping to header file is broken on Windows.

### ISSUE THREAD

**Issue by amosbird** [syohex/emacs-helm-gtags#136]
Tags come with this `^M` trailing character, leading to create new files instead of jumping.
![gg9l e19rn n d 1j0yg](https://cloud.githubusercontent.com/assets/5085485/11580723/2a17fc66-9a75-11e5-9f98-2e335ce7b46f.png)

**Comment by amosbird** [comment]
Does this issue belong to `gtags`? I find that all the tags are ended with Windows `CRLF`.
![asuo_ qfjquv9c xb 70as](https://cloud.githubusercontent.com/assets/5085485/11580771/c0721476-9a75-11e5-84e2-862a3a83ed6b.png)

**Comment by syohex** [comment]
Thanks for reporting issue.
I have fixed this issue at #137. Please check latest version.

**Comment by amosbird** [comment]
Thanks!
