### ISSUE TITLE
relative path in helm-gtags-select-path?

### ISSUE THREAD

**Issue by xin-jin** [syohex/emacs-helm-gtags#139]
Is it possible to display file names  with relative paths in `helm-gtags-select-path`? `helm-gtags-path-style` does not seem to affect it.

**Comment by syohex** [comment]
Thanks for reporting issue. I have fixed at #140. Please check latest version. Here is relative path demo.

![relative](https://cloud.githubusercontent.com/assets/554281/12378004/e5caf046-bd73-11e5-9860-994a1ff149aa.gif)

**Comment by xin-jin** [comment]
Thanks! The latest version does resolve the issue.
