### ISSUE TITLE
Cannot set "C-," as prefix key

### ISSUE THREAD

**Issue by introom** [syohex/emacs-helm-gtags#149]
Hi,
Due to this line: https://github.com/syohex/emacs-helm-gtags/blob/master/helm-gtags.el#L1267

I cannot set "C-," as prefix key.

A simple fix might wrap a kbd:

(kbd (concat prefix " h"))

**Comment by syohex** [comment]
Thanks for reporting issue and sorry too late reply. I have this issue at #150. Please check latest version. And you need to use `C-,`(not escaped) instead of `\C-,`.
