### ISSUE TITLE
Can you add support for ivy-mode?

### ISSUE THREAD

**Issue by redguardtoo** [syohex/emacs-helm-gtags#153]
https://github.com/abo-abo/swiper

" Ivy aims to be more efficient, smaller, simpler, and smoother to use yet highly customizable."

**Comment by syohex** [comment]
No. helm-gtags depends helm heavily, it uses not only completion features but also helm utilities. I suppose that to create other package `ivy-gtags` is better than that helm-gtags supports ivy-mode for package maintenance.

**Comment by redguardtoo** [comment]
Thanks for the answer.
