### ISSUE TITLE
Cannot find tags start with '<'

### ISSUE THREAD

**Issue by amosbird** [syohex/emacs-helm-gtags#154]
This issue happens when I try to jump to tags in a thrift file. I've customized `gtags` to generate thrift tags. Most symbols work just fine. However it cannot jump to tags when the symbol on cursor begins with a '<'. This won't happen in c++ or java mode. How can I debug this?

Failing case:
```thrift
struct A {
  1: required set<B> bad
                  ^
}
```

Working case:
```thrift
struct A {
  1: required set<  B> good
                    ^
}
```

**Comment by syohex** [comment]
Please check symbol table. I suppose it set `<` as symbol character. Please add following configuration or evaluate it and try again.

```
(modify-syntax-entry ?< ".") ;; Set '<' character as punctuation character
```

**Comment by amosbird** [comment]
It works. Thanks!
