### ISSUE TITLE
cannot create tag in current directory.

### ISSUE THREAD

**Issue by amosbird** [syohex/emacs-helm-gtags#162]
![](https://ptpb.pw/jJeP.jpg)

Well, this is not a blocking issue, but quite uncomfortable. I have to go up one directory level to select current directory. Can we have a current directory item inside helm buffer?

**Comment by syohex** [comment]
Could you tell me how to reproduce this issue ? `helm-gtags-create-tags` can create tag in current directory.

![create-tag-in-current-dir](https://cloud.githubusercontent.com/assets/554281/21742365/bec554e8-d530-11e6-9629-d058824bebf4.gif)

**Comment by amosbird** [comment]
hmm, seems like `spacemacs` to blame.
