### ISSUE TITLE
tag references did not update

### ISSUE THREAD

**Issue by huangguiyang** [syohex/emacs-helm-gtags#163]
> emacs version: 25.1.1 (macos)
> Package-Version: 20160917.2238
> Version: 1.5.6

For example, after I rename a function `foo` to `bar`, update all related function call occurrences `foo()` with `bar()` and save them. `helm-gtags-find-rtag` can't find references of `bar` unless I run `gtags` in the source directory manually or run `helm-gtags-find-rtag` in emacs with command prefix 'C-u'.

**Comment by syohex** [comment]
Yes, you need to update global tag when you rename function/symbol names.

**Comment by huangguiyang** [comment]
Can helm-gtags do it automatically?

**Comment by syohex** [comment]
Set `helm-gtags-auto-update` non-nil and enable helm-gtags-mode, then helm-gtags updates tag at file saving time.

**Comment by huangguiyang** [comment]
Yes, I do. But helm-gtags only update GTAGS, but GRTAGS file is not updated.

**Comment by huangguiyang** [comment]
It seems that the option `--single-update` may be the reason.

**Comment by syohex** [comment]
Ah, I see.

**Comment by syohex** [comment]
Please update tag manually in this case. Sorry.

**Comment by huangguiyang** [comment]
OK. Waiting for your fix →_→
