### ISSUE TITLE
sometimes terminal emacs blinks when jumping to tag

### ISSUE THREAD

**Issue by introom** [syohex/emacs-helm-gtags#166]
Hi,

Inside terminal (tested both on terminal.app and iterm2),
emacs will sometimes blink if it jumps to a tag.

For the blink behavior, a video is here to demonstrate:  https://vimeo.com/205775103    

What's the cause of it?  Is it due to the action of invoking the process `global' to query the GTAGS database? 

I'd like to submit a patch, but I dunno how to find out what makes the blinking.

**Comment by syohex** [comment]
Because helm-gtags.el calls `pulse-momentary-highlight-one-line` after jumping. You can disable it by setting `helm-gtags-pulse-at-cursor` to `nil`.

**Comment by introom** [comment]
No.  This is not the effect I was describing.

It's the whole emacs frame flashes, not highlighting on some line.

See the above vimeo video.

**Comment by syohex** [comment]
Ah, sorry.

I suppose it is caused by `recenter` and please set `recenter-redisplay` to `nil` and try again.

**Comment by introom** [comment]
Thanks! It works.
