### ISSUE TITLE
Enable fuzzy matching

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-helm-gtags#88]
Recently Helm added support for fuzzy matching to any source specified to do so with this [commit](https://github.com/emacs-helm/helm/commit/8252db467e0f3e206877eb1830602a286da04598). 

If you create helm source with defvar, you can enable it with this:

```lisp
(match . helm-fuzzy-match)
```

It will be useful for `helm-gtags-select`, `helm-gtags-find-tag` and `helm-gtags-reference`.

**Comment by syohex** [comment]
I fixed at #91. Please check latest version.

**Comment by tuhdo** [comment]
Thank you.
