### ISSUE TITLE
helm-gtags-select doesn't work in 1.4.3

### ISSUE THREAD

**Issue by mofaph** [syohex/emacs-helm-gtags#94]
For example, in a project root, input command:

M-x helm-gtags-select RET hello

helm give me:

hello1
hello2

When the cursor in hello1, if I press RET, it should jump to the definition, but it doesn't.

1.4.2 was working.

Thanks.

**Comment by syohex** [comment]
I confirmed the issue. I'll find bug.

**Comment by syohex** [comment]
@mofaph I've fixed this issue at #94. Please check latest version.

**Comment by mofaph** [comment]
@syohex OK. It works for me. Good work, thanks! :-)

**Comment by syohex** [comment]
Thanks for checking, I'll release new version soon.
