### ISSUE TITLE
byte-code: No buffer named  *helm-gtags-update-tag*

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-helm-gtags#96]
To reproduce:

- Connect to a remote via Tramp (i.e. connect to a VM).
- Open a buffer with `helm-gtags` enabled.
- Copy something and paste there.
- Error happens: `No buffer named  *helm-gtags-update-tag*` whenever we try to run any command. It makes saving buffer impossible.

**Comment by syohex** [comment]
@tuhdo I fixed at #97. Please check latest version.
